[tasks.build_macos_arm]
info = "aarch64 binary"
script = "wails build --clean --platform darwin/arm64"

[tasks.build_macos_intel]
info = "x86_64 binary"
script = "wails build --clean --platform darwin"

[tasks.build_macos]
info = "universal2 binary"
script = "wails build --clean --platform darwin/universal"

[tasks.build_windows]
info = "x86_64 binary"
script = "wails build --clean --platform windows/amd64"

[tasks.build_linux]
info = "x86_64 binary"
script = "wails build --clean --platform linux/amd64"

[tasks.build_all]
info = "build lilith launcher binary for all platforms"
script = ["maid build_macos_arm", "maid build_macos_intel", "maid build_macos", "maid build_windows", "maid build_linux"]

[tasks]
clean = { info = "remove lilith files", path = "build", script = ["rm -rf %{dir.home}/lilith", "rm -rf bin"] }
kill = { info = "kill lilith backend", script = "killall 'lilith-*'" }
dev = { info = "run lilith launcher", script = "wails dev" }
install = { info = "install wails", script = "go install github.com/wailsapp/wails/v2/cmd/wails@latest" }
build = { info = "build lilith launcher binary (for platform)", script = "wails build --clean" }