name: Build Application

on: [push, pull_request]

jobs:
  build:
    name: Build Application
    if: "contains(github.event.head_commit.message, '[run build]')"
    strategy:
      fail-fast: false
      matrix:
        build:
          [
            { name: lilith_launcher, platform: linux/amd64, os: ubuntu-latest },
            { name: lilith_launcher, platform: windows/amd64, os: windows-latest },
            { name: lilith_launcher, platform: darwin/universal, os: macos-latest },
          ]
    runs-on: ${{ matrix.build.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: theMackabu/wails-build-action@main
        with:
          build-name: ${{ matrix.build.name }}
          build-platform: ${{ matrix.build.platform }}
          package: false
