name: build
on:
  push:
jobs:
  build:
    name: Test Build Latest Release
    if: "contains(github.event.head_commit.message, '[run build]')"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
      - name: Set up Go 1.16
        uses: actions/setup-go@v1
        with:
          go-version: 1.17
        id: go

      - name: Checkout the repo
        uses: actions/checkout@v1

      - name: Get wails build tool
        run: |
          go install github.com/wailsapp/wails/v2/cmd/wails@latest

      - name: Build application
        run: wails build
