name: Release Application

on: push

jobs:
  build:
    name: Release Application
    if: "contains(github.event.head_commit.message, '[release')"
    strategy:
      fail-fast: false
      matrix:
        build:
          [
            { name: lilith_launcher, platform: linux/amd64, os: ubuntu-latest },
            { name: lilith_launcher, platform: windows/amd64, os: windows-latest },
            { name: lilith_launcher, platform: darwin/universal, os: macos-latest },
          ]
    runs-on: ${{ matrix.build.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: dAppServer/wails-build-action@v2
        with:
          build-name: ${{ matrix.build.name }}
          build-platform: ${{ matrix.build.platform }}
          package: true
